name: deployDevCon
on: 
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initial Checkout
        uses: actions/checkout@v3
      - name: Use devcon cli to build container
        uses: devcontainers/ci@v0.2
        with:
          runCmd: 'make ci-build'