name: deployDevCon
on: 
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initial Checkout
        uses: actions/checkout@v3
      
      - name: Login to GitHub Container Reg
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Download devcontainer/cli
        uses: echo 'npm install -g @devcontainer/cli'

      - name: build the dev container
        uses: echo 'devcontainer build .'

      # - name: Use devcon cli to build container
      #   uses: devcontainers/ci@v0.2
      #   with:
      #     imageName: 'ghcr.io/richross/dotnet/sdk6'
      #     imageTag: 'latest'
      #     runCmd: |
      #       dotnet --version
      #       ls